apiVersion: operator.openshift.io/v1              
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  nodePlacement:
    nodeSelector:
      matchLabels:
        kubernetes.io/node-role: infra
