apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: '{{ fromClusterClaim "name" }}'
spec:
  text: '{{ fromConfigMap "console-notifications" "console-notification" (fromClusterClaim "environment") }} OpenShift version {{ fromClusterClaim "version.openshift.io" }}.'
  location: BannerTop
  color: '#fff'
  backgroundColor: '#0088ce'
